In [10]:
import torch

In [11]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 45, -57,  55,  25, -24,  74])

In [12]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [13]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
# a tensor with inf or -inf numbers
ins = torch.empty(2, 3)
ins

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [17]:
# linear space with constant increment
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [18]:
logspace = torch.logspace(-10, 10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [19]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [28]:
# 10% => 0, 90% => 1
prob = torch.tensor([0.1, 0.9])
samples = torch.multinomial(prob, num_samples=10, replacement=True)
samples

tensor([1, 1, 1, 1, 1, 1, 1, 0, 0, 1])

In [29]:
# useful in generating text with n-grams
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [30]:
# triangle lower
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [31]:
# triangle upper
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [32]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float("-inf"))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [33]:
out = torch.exp(out)
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [34]:
ins = torch.zeros(2, 3, 4)
out = ins.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [35]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
import torch.nn as nn

# create a linear layer who has input and output as {in/out}_features
# y = x * W^T + b
# where y is out_tensor, x is in_tensor, W is weight matrix (randomly initiated), b is bias vector.
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(in_features=3, out_features=3, bias=False)
linear(sample)

tensor([-8.2695, -4.6615,  3.0892], grad_fn=<SqueezeBackward4>)

In [36]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [56]:
# dot product of arrays
mult = torch.tensor([1, 2, 3]) @ torch.tensor([4, 5, 6])
mult

tensor(32)

In [55]:
# matrix multiplication
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
mult = a @ b # same as torch.matmul(a, b)
mult

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [59]:
a = torch.rand(2, 3, 5)
print("a")
print(a)
x, y, z = a.shape
a = a.view(x * y, z)
print("a after")
print(a)

a
tensor([[[0.0988, 0.4628, 0.9720, 0.0531, 0.8422],
         [0.6565, 0.4874, 0.6860, 0.8290, 0.9682],
         [0.0549, 0.2790, 0.6416, 0.2638, 0.0690]],

        [[0.9289, 0.5462, 0.3191, 0.6897, 0.9449],
         [0.1080, 0.8168, 0.2613, 0.1820, 0.3217],
         [0.6902, 0.5851, 0.7183, 0.0020, 0.5037]]])
a after
tensor([[0.0988, 0.4628, 0.9720, 0.0531, 0.8422, 0.6565, 0.4874, 0.6860, 0.8290,
         0.9682, 0.0549, 0.2790, 0.6416, 0.2638, 0.0690],
        [0.9289, 0.5462, 0.3191, 0.6897, 0.9449, 0.1080, 0.8168, 0.2613, 0.1820,
         0.3217, 0.6902, 0.5851, 0.7183, 0.0020, 0.5037]])
